### ISSUE TITLE
allow wildcards or regular expressions in campaign search

### ISSUE THREAD

**Issue by slava77** [cms-PdmV/ValDB2#50]
https://cms-pdmv-prod.web.cern.ch/valdb/campaigns

doesn't seem to allow wildcard in the search

e.g. 
<img width="900" alt="image" src="https://github.com/cms-PdmV/ValDB2/assets/4676718/1e974ee4-3a3a-41d8-b9d0-e1f671ffe452">

I wanted to select a subset to use in the comparisons

**Comment by ggonzr** [comment]
Hello @slava77,

Please format the regex following the [PCRE](https://learnxinyminutes.com/docs/pcre/) guidelines. For the given query, it would be 13_3_0_.*_2023

Best,
Geovanny

**Comment by slava77** [comment]
thanks, it works; I thought I tried `.*` before opening the issue, but apparently I didn't really
